### ISSUE TITLE
ddp example

### ISSUE THREAD

**Issue by alicera** [pytorch/examples#1143]
## 📚 Documentation

https://github.com/pytorch/examples/tree/main/distributed/ddp#argument-passing-convention

Here it say " --local_world_size: This is passed in explicitly and is typically either  or the number of GPUs per node. "

I can't understand this example.
Why --local_world_size=1   not  8

Similarly, it can be launched with a single process that spans all 8 GPUs using:
```
python /path/to/launch.py --nnode=1 --node_rank=0 --nproc_per_node=1 example.py --local_world_size=1

```

**Comment by alicera** [comment]
python /path/to/launch.py --nnode=1 --node_rank=0 --nproc_per_node=1 example.py --local_world_size=1

There are 4 gpus (same) on machine

the error is 

```
 warnings.warn(
[7320] Initializing process group with: {'MASTER_ADDR': '127.0.0.1', 'MASTER_PORT': '29500', 'RANK': '0', 'WORLD_SIZE': '1'}
[7320]: world_size = 1, rank = 0, backend=nccl 
[7320] rank = 0, world_size = 1, n = 4, device_ids = [0, 1, 2, 3] 
Traceback (most recent call last):
  File "example.py", line 97, in <module>
    spmd_main(args.local_world_size, args.local_rank)
  File "example.py", line 83, in spmd_main
    demo_basic(local_world_size, local_rank)
  File "example.py", line 39, in demo_basic
    ddp_model = DDP(model, device_ids)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 484, in __init__
    self._log_and_throw(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 604, in _log_and_throw
    raise err_type(err_msg)
ValueError: device_ids can only be None or contain a single element.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 7320) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-29_05:08:15
  host      : ml2
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 7320)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```
