### ISSUE TITLE
vision_transformer/main.py fails: TypeError: '_Faketqdm' object is not iterable

### ISSUE THREAD

**Issue by yurivict** [pytorch/examples#1148]
[This](https://github.com/pytorch/examples/blob/main/vision_transformer/main.py) example fails:
```
$ python3.9 main.py 
Files already downloaded and verified
Files already downloaded and verified
Error in cpuinfo: operating system is not supported in cpuinfo
Traceback (most recent call last):
  File "/usr/ports/misc/py-torchvision/main.py", line 263, in <module>
    main()
  File "/usr/ports/misc/py-torchvision/main.py", line 259, in main
    TrainEval(args, model, train_loader, valid_loader, optimizer, criterion, device).train()
  File "/usr/ports/misc/py-torchvision/main.py", line 183, in train
    train_loss = self.train_fn(i)
  File "/usr/ports/misc/py-torchvision/main.py", line 144, in train_fn
    for t, data in enumerate(tk):
TypeError: '_Faketqdm' object is not iterable
```

## Context
* Pytorch version: 2.0.0
* Operating System and version: FreeBSD 13.2

**Comment by msaroufim** [comment]
Ah I believe this should be fixed if you just `pip install tqdm`
