### ISSUE TITLE
no any output when I try ddp and dataParallelism

### ISSUE THREAD

**Issue by YihuaXuCn** [pytorch/examples#1154]
## Context

I am a freshman using DDP, so I directly use the code in this repo. The code can run in my environment, but there is no output. The reason for ensuring the code has been executed is two points.  The first bit is that I checked GPUs usage, and the 2nd bit is that a "checkpoint.pt" file has been created. 

* Pytorch version: 2.0.1+cu117
* Operating System and version: Ubuntu 20.04.4 LTS

# Environment

* GPU environment:
```
Thu May 25 03:15:52 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    Off  | 00000000:01:00.0 Off |                  Off |
| 30%   44C    P2    96W / 300W |    827MiB / 49140MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000    Off  | 00000000:41:00.0 Off |                  Off |
| 30%   42C    P2    99W / 300W |    835MiB / 49140MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA RTX A6000    Off  | 00000000:81:00.0 Off |                  Off |
| 30%   49C    P2    97W / 300W |    835MiB / 49140MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA RTX A6000    Off  | 00000000:C1:00.0 Off |                  Off |
| 30%   43C    P2    87W / 300W |    795MiB / 49140MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   3767550      C   .../envs/xxxxxxxx/bin/python      825MiB |
|    1   N/A  N/A   3767551      C   .../envs/xxxxxxxx/bin/python      833MiB |
|    2   N/A  N/A   3767552      C   .../envs/xxxxxxxx/bin/python      833MiB |
|    3   N/A  N/A   3767553      C   .../envs/xxxxxxxx/bin/python      793MiB |
+-----------------------------------------------------------------------------+
```

* Which example are you using: I am working on the "main" branch. I almost did not change any code in the file "examples/distributed/ddp-tutorial-series/multigpu.py" except adding some print statements. For example,  in `main` function
 ```
    dataset, model, optimizer = load_train_objs()
    print("load train objs")
    train_data = prepare_dataloader(dataset, batch_size)
    print("load data")
    trainer = Trainer(model, train_data, optimizer, rank, save_every)
    print("create instance of Traniner")
    trainer.train(total_epochs)
```

## Expected Behavior

it should finished in seconds based on my command `python multiplegpu.py 10 5 > output.txt` and print out something like `[GPU: 0 ...` `[GPU 1 ... ` `[GPU: 2 ...` `[GPU 3 ... ` into the file `output.txt`
but the code will spend several hours without output, even without error.

**Comment by asimay** [comment]
Hi
I came across the same issue:

please see the scree shot:

**Comment by asimay** [comment]
and after a long time, the APP is crash:

[E ProcessGroupNCCL.cpp:475] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=1800000) ran for 1800263 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:475] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=1800000) ran for 1800316 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=1800000) ran for 1800316 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=1800000) ran for 1800263 milliseconds before timing out.

**Comment by asimay** [comment]
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/home/xxx/work/xxx/xxx-main/src/multigpu.py", line 102, in main
    trainer = Trainer(model, train_data, optimizer, rank, save_every)
  File "/home/xxx/work/xxx/xxx-main/src/multigpu.py", line 50, in __init__
    self.model = DDP(model, device_ids=[gpu_id])
  File "/home/xxx/.local/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 795, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/xxx/.local/lib/python3.9/site-packages/torch/distributed/utils.py", line 265, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: DDP expects same model across all ranks, but Rank 0 has 2 params, while rank 1 has inconsistent 0 params.
