### ISSUE TITLE
adding CUDA support in reinforcement_learning

### ISSUE THREAD

**Issue by dusty-nv** [pytorch/examples#165]
I'm attempting to add CUDA to [actor_critic.py](https://github.com/pytorch/examples/blob/master/reinforcement_learning/actor_critic.py) and [reinforce.py](https://github.com/pytorch/examples/blob/master/reinforcement_learning/reinforce.py)

What do I need to use other than `policy.cuda()`?   I also have the basic argument parsing and seeding stuff already.  However after enabling `policy.cuda()`, I am left with a message:

```
Traceback (most recent call last):
  File "reinforce.py", line 58, in <module>
    optimizer.cuda()
AttributeError: 'Adam' object has no attribute 'cuda'
dusty@sky-x4e2:~/workspace/jetson-reinforcement/build/pytorch/examples/reinforcement_learning$ python reinforce.py --cuda
[2017-06-06 13:16:36,109] Making new env: CartPole-v0
Traceback (most recent call last):
  File "reinforce.py", line 89, in <module>
    action = select_action(state)
  File "reinforce.py", line 62, in select_action
    probs = policy(Variable(state))
  File "/home/dusty/workspace/jetson-reinforcement/build/pytorch/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "reinforce.py", line 48, in forward
    x = F.relu(self.affine1(x))
  File "/home/dusty/workspace/jetson-reinforcement/build/pytorch/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dusty/workspace/jetson-reinforcement/build/pytorch/torch/nn/modules/linear.py", line 54, in forward
    return self._backend.Linear.apply(input, self.weight, self.bias)
  File "/home/dusty/workspace/jetson-reinforcement/build/pytorch/torch/nn/_functions/linear.py", line 12, in forward
    output.addmm_(0, 1, input, weight.t())
TypeError: addmm_ received an invalid combination of arguments - got (int, int, torch.FloatTensor, torch.cuda.FloatTensor), but expected one of:
 * (torch.FloatTensor mat1, torch.FloatTensor mat2)
 * (torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
 * (float beta, torch.FloatTensor mat1, torch.FloatTensor mat2)
 * (float alpha, torch.FloatTensor mat1, torch.FloatTensor mat2)
 * (float beta, torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
 * (float alpha, torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
 * (float beta, float alpha, torch.FloatTensor mat1, torch.FloatTensor mat2)
      didn't match because some of the arguments have invalid types: (int, int, torch.FloatTensor, torch.cuda.FloatTensor)
 * (float beta, float alpha, torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
      didn't match because some of the arguments have invalid types: (int, int, torch.FloatTensor, torch.cuda.FloatTensor)
```
It looks like some conversion is necessary between the policy and optimizer.  
What objects should I be calling `.cuda()` on?

**Comment by apaszke** [comment]
It seems that you didn't `cuda()` the input

**Comment by dusty-nv** [comment]
Hmm thanks for your reply, I try `state.cuda()` and `reward.cuda()` and also below, but with the same error message:

`autograd.backward(policy.saved_actions.cuda(), [None for _ in policy.saved_actions.cuda()])`

Taken from this [DQN tutorial](http://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html), I also used the below with the same results:

```
FloatTensor = torch.cuda.FloatTensor if args.cuda else torch.FloatTensor
LongTensor = torch.cuda.LongTensor if args.cuda else torch.LongTensor
ByteTensor = torch.cuda.ByteTensor if args.cuda else torch.ByteTensor
Tensor = FloatTensor
```

Interestingly all the DQN tutorial did was `model.cuda()` with the above and it worked there.

**Comment by msaroufim** [comment]
Stale issue
