### ISSUE TITLE
cPickle.UnpicklingError

### ISSUE THREAD

**Issue by pannous** [pytorch/examples#169]
```
>~/pytorch/examples/fast_neural_style$ python neural_style/neural_style.py eval --content-image images/content-images/amber.jpg --model images/style-images/mosaic.jpg --output-image t.png --cuda 0
Traceback (most recent call last):
  File "neural_style/neural_style.py", line 227, in <module>
    main()
  File "neural_style/neural_style.py", line 223, in main
    stylize(args)
  File "neural_style/neural_style.py", line 151, in stylize
    style_model.load_state_dict(torch.load(args.model))
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 229, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 367, in _load
    magic_number = pickle_module.load(f)
cPickle.UnpicklingError: invalid load key, '?'.
```

**Comment by pannous** [comment]
>>> torch.version.__version__
'0.1.12_2'

**Comment by apaszke** [comment]
You gave a path to a `.jpg` file as a model checkpoint.

**Comment by The-Gupta** [comment]
`import torch
import torch.autograd
import torch.nn
import torch.multiprocessing
import torch.utils
import torch.legacy.nn
import torch.legacy.optim

xp = torch.load(r"D:\SDS\1_MachineLearning\amr-eager-master\LDC2015E86\reentrancies.dat")

Traceback (most recent call last):

  File "<ipython-input-10-c4a3fa896893>", line 9, in <module>
    xp = torch.load(r"D:\SDS\1_MachineLearning\amr-eager-master\LDC2015E86\reentrancies.dat")

  File "D:\Anaconda3\envs\amr-eager\lib\site-packages\torch\serialization.py", line 261, in load
    return _load(f, map_location, pickle_module)

  File "D:\Anaconda3\envs\amr-eager\lib\site-packages\torch\serialization.py", line 399, in _load
    magic_number = pickle_module.load(f)

UnpicklingError: invalid load key, ''.`

I'm loading a model available [here](http://kinloch.inf.ed.ac.uk/public/direct/amreager/LDC2015E86.tar.gz).
