### ISSUE TITLE
Error when running neural style transfer

### ISSUE THREAD

**Issue by fakufaku** [pytorch/examples#171]
I get an error when running the neural style transfer example. I haven't modified the example in any way at this point.

CUDA version is 8.0. Torch version is 0.1.12+8d33603. OS X is 10.12.4. I am using Python 3.5.3 with Anaconda.

I run
```
python neural_style/neural_style.py eval --content-image ~/Desktop/BioPic/robin.png --model saved_models/mosaic.pth --output-image ~/Desktop/robin.png --cuda 1
```
with output
```
Traceback (most recent call last):
  File "neural_style/neural_style.py", line 226, in <module>
    main()
  File "neural_style/neural_style.py", line 222, in main
    stylize(args)
  File "neural_style/neural_style.py", line 153, in stylize
    output = style_model(content_image)
  File "/Users/scheibler/anaconda/envs/python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/scheibler/sandbox/pytorch-examples/fast_neural_style/neural_style/transformer_net.py", line 30, in forward
    y = self.relu(self.in1(self.conv1(X)))
  File "/Users/scheibler/anaconda/envs/python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/scheibler/sandbox/pytorch-examples/fast_neural_style/neural_style/transformer_net.py", line 53, in forward
    out = self.conv2d(out)
  File "/Users/scheibler/anaconda/envs/python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/scheibler/anaconda/envs/python3/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 244, in forward
    self.padding, self.dilation, self.groups)
  File "/Users/scheibler/anaconda/envs/python3/lib/python3.5/site-packages/torch/nn/functional.py", line 48, in conv2d
    return f(input, weight, bias)
RuntimeError: Need input.size[1] == 3 but got 4 instead.
```

**Comment by abhiskk** [comment]
Hey @fakufaku , I just tested the code again and it works for me. I think there might be some issue using the CUDA version of code on OSX, can you try running the code with the option `--cuda 0`. Also can you test with the content image that is present in the repository `/images/content-images/amber.jpg`, it's unlikely but there might be an issue with loading the PNG file format which you are using.

**Comment by fakufaku** [comment]
Hi @abhiskk, thanks for the suggestion. It seems the png image was the culprit. I could successfully run the example on a jpg file. Even like this, my GPU seems too small to run the example (out of memory), but that is a different problem :) (without CUDA, it works fine)
Thanks for your help!
