### ISSUE TITLE
ImageNet Error

### ISSUE THREAD

**Issue by wk910930** [pytorch/examples#178]
Hi,

I am trying to train the models on ImageNet following [this](https://github.com/pytorch/examples/tree/master/imagenet#training). However, I got no luck.

Does anyone know how to fix the following issue?

```shell
kwang@cdc-177:~/PyTorch/examples/imagenet$ CUDA_VISIBLE_DEVICES=1 python main.py -a resnet18 /imagenet_dir
=> creating model 'resnet18'
Traceback (most recent call last):
  File "main.py", line 289, in <module>
    main()
  File "main.py", line 131, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 159, in train
    for i, (input, target) in enumerate(train_loader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "build/bdist.linux-x86_64/egg/torchvision/datasets/folder.py", line 116, in __getitem__
    img = self.loader(path)
  File "build/bdist.linux-x86_64/egg/torchvision/datasets/folder.py", line 63, in default_loader
    return pil_loader(path)
  File "build/bdist.linux-x86_64/egg/torchvision/datasets/folder.py", line 45, in pil_loader
    with Image.open(f) as img:
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 528, in __getattr__
    raise AttributeError(name)
AttributeError: __exit__
```

`PyTorch` is okay and I can run some other experiments with it.

Thanks!

**Comment by wk910930** [comment]
Problem Solved: Actually, it is caused by the PIL (the Python Imaging Library). Try to reinstall PIL via `pip install pillow`.
