### ISSUE TITLE
size mismatch error while forward pass in the Regression example

### ISSUE THREAD

**Issue by Dawny33** [pytorch/examples#198]
The [line](https://github.com/pytorch/examples/blob/86bc3e516dde92fee0ce00668a3714c03155dd44/regression/main.py#L54) throws the following error:

`RuntimeError: size mismatch, m1: [32 x 1], m2: [4 x 1] at /pytorch/torch/lib/TH/generic/THTensorMath.c:1293`

The complete error trace is:

```
Traceback (most recent call last):
  File "regression.py", line 81, in <module>
    output = F.smooth_l1_loss(fc(batch_x), batch_y)  #Forward pass with a smooth l loss as the loss function
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/linear.py", line 53, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 553, in linear
    return torch.addmm(bias, input, weight.t())
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 924, in addmm
    return cls._blas(Addmm, args, False)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 920, in _blas
    return cls.apply(*(tensors + (alpha, beta, inplace)))
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/_functions/blas.py", line 26, in forward
    matrix1, matrix2, out=output)
RuntimeError: size mismatch, m1: [32 x 1], m2: [4 x 1] at /pytorch/torch/lib/TH/generic/THTensorMath.c:1293
```

OS: Ubuntu14.04

**Comment by lynic** [comment]
Can not reproduce this problem on 0.2.0, do you change anything? get_batch should return variable with shape (32,4) and (4,1)

**Comment by Dawny33** [comment]
@lynic Sorry. It was my problem. My both `bactch_x` and `batch_y` were the same.  

Closing this.
