### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe When i :"run cifar10_tutorial.py"

### ISSUE THREAD

**Issue by keloli** [pytorch/examples#201]
Hi Soumith,

I download "cifar10_tutorial.py"from http://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html.
When I run this file in Spyder on Windows10, it reports"BrokenPipeError: [Errno 32] Broken pipe", the details information are as follows:

> runfile('D:/PyTorch/Code/LearnPyTorch/cifar10_tutorial.py', wdir='D:/PyTorch/Code/LearnPyTorch')
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "<ipython-input-1-8d404f320a32>", line 1, in <module>
    runfile('D:/PyTorch/Code/LearnPyTorch/cifar10_tutorial.py', wdir='D:/PyTorch/Code/LearnPyTorch')
  File "D:\Anaconda\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)
  File "D:\Anaconda\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "D:/PyTorch/Code/LearnPyTorch/cifar10_tutorial.py", line 99, in <module>
    dataiter = iter(trainloader)
  File "D:\Anaconda\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 303, in __iter__
    return DataLoaderIter(self)
  File "D:\Anaconda\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 162, in __init__
    w.start()
  File "D:\Anaconda\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

Could you give me any advise to help me run "cifar10_tutorial.py" successfully? By the way, other examples in "Deep Learning with PyTorch: A 60 Minute Blitz" have been run suceessfully.

**Comment by soumith** [comment]
I'm sorry, I dont know. We dont have an idea about Windows.

**Comment by apurvapatkeshwar** [comment]
On a Windows machine, you may need to wrap your multiprocessing code inside:
`if __name__ == '__main__'`
