### ISSUE TITLE
torch.load model error 

### ISSUE THREAD

**Issue by lykiller** [pytorch/examples#205]
i use the main.cpp in imageNet to training my own model
and in the test ,it appears an error in pytorch model .

    model = torchvision.models.densenet121(pretrained=False)
    model.fc = nn.Linear(1024, 96)
    model = torch.nn.DataParallel(model).cuda()
    checkpoint = torch.load("model.pth.tar")
    model.load_state_dict(checkpoint['state_dict'])
Error:
    Traceback (most recent call last):
  File "test.py", line 101, in <module>
    main()
  File "test.py", line 56, in main
    checkpoint = torch.load("model.pth.tar")
  File "/home/ly/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 231, in load
    return _load(f, map_location, pickle_module)
  File "/home/ly/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 364, in _load
    return legacy_load(f)
  File "/home/ly/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 302, in legacy_load
    tar.extract('storages', path=tmpdir)
  File "/home/ly/anaconda2/lib/python2.7/tarfile.py", line 2109, in extract
    tarinfo = self.getmember(member)
  File "/home/ly/anaconda2/lib/python2.7/tarfile.py", line 1829, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'storages' not found"

**Comment by nsaphra** [comment]
This is an unfortunate effect of using pickle as the core of serialization for pytorch. Does this error also occur if you load from within the same directory that contains your model code?

**Comment by kvgallagher** [comment]
I'm having the same issue. Error also occurs when loading from same directory as model. 

Any suggestions on resolving?

**Comment by ShuvenduBikash** [comment]
@nsaphra Yes, it does!! After so long time still the same problem! And no answer in this issue!!

**Comment by suraj813** [comment]
Seems outdated, closing this issue. Please reopen if it persists in current pytorch versions
