### ISSUE TITLE
CUDA error running on multiple GPUs: torch.cuda.nccl.NcclError: System Error (2)

### ISSUE THREAD

**Issue by adrianalbert** [pytorch/examples#246]
Hi,

I've been trying to run the example code (on the maps dataset):

python main.py --ngpu 4 --dataset folder --dataroot /home/data/CelebA/splits --cuda

I get the error below related to the NCCL library. I'm trying to run this on 4 K80 GPUs. The above command works fine in CPU-only mode as well as when training on just one GPU (--ngpu 1).

I'm running NVIDIA CUDA 8.0 and pytorch 0.2 in a docker image on a server with 256GB RAM. 

I tried this with other [architectures](https://github.com/carpedm20/DiscoGAN-pytorch/issues/12), and get the same error. It must be related to the CUDA

Any suggestions on what could be causing this and what a solution could be?

Traceback (most recent call last):
  File "main.py", line 225, in <module>
    output = netD(inputv)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in
 __call__
    result = self.forward(*input, **kwargs)
  File "main.py", line 174, in forward
    output = nn.parallel.data_parallel(self.main, input, range(self.ngpu))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line
 104, in data_parallel
    replicas = replicate(module, used_device_ids)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/replicate.py", line 12,
 in replicate
    param_copies = Broadcast(devices)(*params)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/_functions.py", line 19
, in forward
    outputs = comm.broadcast_coalesced(inputs, self.target_gpus)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/comm.py", line 54, in broadcas
t_coalesced
    results = broadcast(_flatten_tensors(chunk), devices)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/comm.py", line 24, in broadcas
t
    nccl.broadcast(tensors)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/nccl.py", line 182, in broadca
st
    comm = communicator(inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/nccl.py", line 133, in communi
cator
    _communicators[key] = NcclCommList(devices)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/nccl.py", line 106, in __init_
_
    check_error(lib.ncclCommInitAll(self, len(devices), int_array(devices)))
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/nccl.py", line 118, in check_e
rror
    raise NcclError(status)
torch.cuda.nccl.NcclError: System Error (2)

**Comment by oya163** [comment]
Yes somebody should solve this error. Getting when installing pytorch=0.2 with conda.

**Comment by soumith** [comment]
the example has to be run with pytorch version 0.3

**Comment by oya163** [comment]
Is there any other solution to solve this error when we need to run pytorch 0.2 installed with conda?
