### ISSUE TITLE
RuntimeError: reinforce() was removed.

### ISSUE THREAD

**Issue by momeara** [pytorch/examples#257]
With pytorch/examples.git at 62d5ca5 and pytorch/pytorch.git at 8ebf18b (Head on Nov 21 2017)

Running

    cd reinforcement_learning
    python reinforce.py

gives me this error:

````
reinforce.py:43: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(action_scores)
Traceback (most recent call last):
  File "reinforce.py", line 88, in <module>
    finish_episode()
  File "reinforce.py", line 67, in finish_episode
    action.reinforce(r)
  File "/mnt/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/torch/autograd/variable.py", line 213, in reinforce
    """))
RuntimeError: reinforce() was removed.
Use torch.distributions instead.
See http://pytorch.org/docs/master/distributions.html

Instead of:

probs = policy_network(state)
action = probs.multinomial()
next_state, reward = env.step(action)
action.reinforce(reward)
action.backward()

Use:

probs = policy_network(state)
# NOTE: categorical is equivalent to what used to be called multinomial
m = torch.distributions.Categorical(probs)
action = m.sample()
next_state, reward = env.step(action)
loss = -m.log_prob(action) * reward
loss.backward()
````

**Comment by soumith** [comment]
yes, see https://github.com/pytorch/examples/pull/249 for the fix. We'll merge this PR once v0.3.0 is released.

**Comment by momeara** [comment]
Ok thanks.

It works but requires `s/Multinomial/Categorical/g'
