### ISSUE TITLE
imagenet IOError

### ISSUE THREAD

**Issue by muzi-8** [pytorch/examples#282]
I am trying to train the models on ImageNet following [this.](https://github.com/pytorch/examples/tree/master/imagenet) However, There are a problems. As follows

$python pytorch_imagenet.py -a alexnet --lr 0.01 /mnt/yp/muzidoctument/ilsvrc/
=> creating model 'alexnet'
Epoch: [0][0/4969]	Time 14.498 (14.498)	Data 2.862 (2.862)	Loss 6.9080 (6.9080)	Prec@1 0.000 (0.000)	Prec@5 0.000 (0.000)
Traceback (most recent call last):
  File "pytorch_imagenet.py", line 314, in <module>
    main()
  File "pytorch_imagenet.py", line 156, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "pytorch_imagenet.py", line 184, in train
    for i, (input, target) in enumerate(train_loader):
  File "/home/muzi-18/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 187, in __next__
    return self._process_next_batch(batch)
  File "/home/muzi-18/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/home/muzi-18/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/muzi-18/anaconda2/lib/python2.7/site-packages/torchvision/datasets/folder.py", line 116, in __getitem__
    img = self.loader(path)
  File "/home/muzi-18/anaconda2/lib/python2.7/site-packages/torchvision/datasets/folder.py", line 63, in default_loader
    return pil_loader(path)
  File "/home/muzi-18/anaconda2/lib/python2.7/site-packages/torchvision/datasets/folder.py", line 45, in pil_loader
    with Image.open(f) as img:
  File "/home/muzi-18/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 2585, in open
    % (filename if filename else fp))
**IOError: cannot identify image file** <open file '/mnt/yp/muzidoctument/ilsvrc/train/n09332890/n09332890_20644.JPEG', mode 'rb' at 0x7f1fc5637ed0>

Does anyone know how to fix the following issue? or any suggestion?
Thanks!

**Comment by SsnL** [comment]
If you look at the trace, the problem is that Pillow is having trouble loading the `/mnt/yp/muzidoctument/ilsvrc/train/n09332890/n09332890_20644.JPEG` image. Could you try and see if you can manually open it in python? Also check your Pillow install for any issues and updates.

**Comment by muzi-8** [comment]
@SsnL 
as you mentioned,I try open the n09332890_20644.JPEG by python.To my surprise,the picture damaged! so there are few images that are damaged in the Imagenet Train Dataset. 
 Thanks for your reply!
