### ISSUE TITLE
Is it possible to run snli: train.py on CPU (without CUDA)?

### ISSUE THREAD

**Issue by dbl001** [pytorch/examples#304]
```
$ conda list pytorch
# packages in environment at /Users/davidlaxer/anaconda:
#
pytorch                   0.2.0                py27_4cu75    soumith

$ export NO_CUDA=0; python train.py 
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    torch.cuda.set_device(args.gpu)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/torch/cuda/__init__.py", line 162, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: 'module' object has no attribute '_cuda_setDevice'
```

**Comment by suraj813** [comment]
Fixed in https://github.com/pytorch/examples/pull/591

**Comment by dbl001** [comment]
Should we upgrade ’from text.legacy import data’ the older pytorch call in train.py line 9?

**Comment by suraj813** [comment]
@dbl001 feel free to raise a PR for this, I'm happy to review it
