### ISSUE TITLE
Imagenet script throws exception in PyTorch 0.4

### ISSUE THREAD

**Issue by yurymalkov** [pytorch/examples#341]
https://github.com/pytorch/examples/blob/c7df3c00f10c60b9fadbfc6709d5799c40fcedc7/imagenet/main.py#L189

Got the following error when trying to train imagenet:
```
Traceback (most recent call last):
  File "main.py", line 313, in <module>
    main()
  File "main.py", line 157, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 189, in train
    target = target.cuda(True)
TypeError: cuda(): argument 'device' (position 1) must be torch.device, not bool
```

**Comment by colesbury** [comment]
Thanks!
