### ISSUE TITLE
Getting UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 40

### ISSUE THREAD

**Issue by banibrata** [pytorch/examples#350]
While running this - python main.py --cuda --epochs 6 from word_language_model

 getting this error:
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    corpus = data.Corpus(args.data)
  File "C:\Users\banide\notebooks\examples-master\word_language_model\data.py", line 22, in __init__
    self.train = self.tokenize(os.path.join(path, 'train.txt'))
  File "C:\Users\banide\notebooks\examples-master\word_language_model\data.py", line 32, in tokenize
    for line in f:
  File "C:\Anaconda\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 40: character maps to <undefined>

Looks like if I add encoding="utf8" inside data.py at likes 30 and 39 @ open statement, the error does not occur!

**Comment by suraj813** [comment]
Fixed in https://github.com/pytorch/examples/pull/366
