### ISSUE TITLE
when I training DCGAN with cifar10 happen some problem about runtime error

### ISSUE THREAD

**Issue by cgpeter96** [pytorch/examples#359]
Traceback (most recent call last):
  File "D:\py_workspace\torch\main.py", line 251, in <module>
    main()
  File "D:\py_workspace\torch\main.py", line 207, in main
    output = netD(real_cpu)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\py_workspace\torch\main.py", line 174, in forward
    output = self.main(input)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Calculated padded input size per channel: (2 x 2). Kernel size: (4 x 4). Kernel size can't greater than actual input size at c:\users\administrator\downloads\new-builder\win-wheel\pytorch\aten\src\thnn\generic/SpatialConvolutionMM.c:48

But I use winodws

**Comment by soumith** [comment]
you are giving input that is too small. you should give atleast 64x64

**Comment by cgpeter96** [comment]
I use cifar10 >_< . If i use cifar10,I need modify the conv kernel size?
