### ISSUE TITLE
MacOS - RuntimeError: error executing torch_shm_manager

### ISSUE THREAD

**Issue by l2late** [pytorch/examples#370]
I try to run the super-resolution example but I get a runtime error:

Command:
`$ python3 main.py --upscale_factor 3 --batchSize 4 --testBatchSize 100 --nEpochs 30 --lr 0.001`

Error
```
Namespace(batchSize=4, cuda=False, lr=0.001, nEpochs=30, seed=123, testBatchSize=100, threads=4, upscale_factor=3)
===> Loading datasets
downloading url  http://www2.eecs.berkeley.edu/Research/Projects/CS/vision/bsds/BSDS300-images.tgz
Extracting data
===> Building model
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    train(epoch)
  File "main.py", line 48, in train
    for iteration, batch in enumerate(training_data_loader, 1):
  File "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/utils/data/dataloader.py", line 138, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/utils/data/dataloader.py", line 138, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/utils/data/dataloader.py", line 113, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/storage.py", line 114, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: error executing torch_shm_manager at "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/lib/torch_shm_manager" at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/libshm/core.cpp:125
```

I run on MacOs High Sierra 10.13.4 with Python 3.6.5

**Comment by zkl99999** [comment]
same error, anyone can resolve it?

**Comment by starplanet** [comment]
me too

**Comment by soumith** [comment]
For v1.3.0 release, this affects OSX + pip. OSX + Conda is working.

I'm working on a fix and uploading new OSX binaries. Also tracking in https://github.com/pytorch/pytorch/issues/2125

**Comment by soumith** [comment]
`pip install torch` will fix this now. Sorry for the delay, root-causing it and issuing new binaries took time.
