### ISSUE TITLE
Using Windows, can't train model, getting errors about vgg16, system relies on wget

### ISSUE THREAD

**Issue by aaronjolson** [pytorch/examples#378]
I am trying to work with the  fast_neural_style example https://github.com/pytorch/examples/tree/master/fast_neural_style

I read through the readme several times and downloaded all needed files mentioned, then I ran
```
C:\Users\Aaron\Documents\fast-neural-style>python neural_style/neural_style.py train --dataset train2017 --style-image images/style-images/2.jpg --save-model-dir saved-models --epochs 2 --cuda 1
usage: neural_style.py train [-h] [--epochs EPOCHS] [--batch-size BATCH_SIZE]
                             --dataset DATASET [--style-image STYLE_IMAGE]
                             --vgg-model-dir VGG_MODEL_DIR --save-model-dir
                             SAVE_MODEL_DIR [--image-size IMAGE_SIZE]
                             [--style-size STYLE_SIZE] --cuda CUDA
                             [--seed SEED] [--content-weight CONTENT_WEIGHT]
                             [--style-weight STYLE_WEIGHT] [--lr LR]
                             [--log-interval LOG_INTERVAL]
neural_style.py train: error: the following arguments are required: --vgg-model-dir
```
Which the readme says nothing about. I then made an empty directory in the project root called vgg and ran the command again
```
(base) C:\Users\Aaron\Documents\fast-neural-style>python neural_style/neural_style.py train --dataset train2017 --style-image images/style-images/2.jpg --vgg-model-dir vgg  --save-model-dir saved-models --epochs 2 --cuda 1
C:\Users\Aaron\Anaconda3\lib\site-packages\torchvision\transforms\transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
'wget' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "neural_style/neural_style.py", line 210, in <module>
    main()
  File "neural_style/neural_style.py", line 204, in main
    train(args)
  File "neural_style/neural_style.py", line 41, in train
    utils.init_vgg16(args.vgg_model_dir)
  File "C:\Users\Aaron\Documents\fast-neural-style\neural_style\utils.py", line 70, in init_vgg16
    vgglua = load_lua(os.path.join(model_folder, 'vgg16.t7'))
  File "C:\Users\Aaron\Anaconda3\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 606, in load_lua
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'vgg\\vgg16.t7'
```
So I went and downloaded wget for Windows https://eternallybored.org/misc/wget/ and added the exe to my path, restarted my Anaconda prompt and now it is downloading a vgg models. 

Made an issue for two reasons
1. this should be mentioned in the README
2. In case anyone else runs into this, this fixed it for me

**Comment by soumith** [comment]
cc: @peterjc123 can you issue to make sure we use cross-platform download command. We can probably even use torch.utils.download_url (or something like that which we have)

**Comment by peterjc123** [comment]
So this issue can be split into 2 parts:
1. Cross-platform file download utilities. Unfortunately, the `download_url` is in `pytorch/vision`, should I move that to `pytorch/pytorch`, @soumith ?
2. Probably cross-platform `load_lua`. I'm sure how to do this. You may have to specify `long_size=8` by yourself.

**Comment by soumith** [comment]
@peterjc123 torch.utils.modelzoo has `_download_url_to_file`, which is probably sufficient?
https://github.com/pytorch/pytorch/blob/master/torch/utils/model_zoo.py#L69

**Comment by soumith** [comment]
about (2), I can re-host the model after it's loaded via `load_lua` and then saved back to disk in Python pickle format

**Comment by peterjc123** [comment]
@soumith Okay!

**Comment by peterjc123** [comment]
@soumith Should I change this in `model_zoo.py` or move it somewhere around?

**Comment by soumith** [comment]
just change it in model_zoo.py for now.
