### ISSUE TITLE
RuntimeError: torch.cuda.FloatTensor is not enabled.

### ISSUE THREAD

**Issue by irazakharchenko** [pytorch/examples#380]
run code this way for imagenet:
 python main.py -a alexnet --lr 0.01 [path]

Gets:
=> creating model 'alexnet'
Traceback (most recent call last):
  File "main.py", line 314, in <module>
    main()
  File "main.py", line 84, in main
    model.cuda()
  File "/mnt/home.stud/zakhairy/myPy/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 249, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/mnt/home.stud/zakhairy/myPy/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/mnt/home.stud/zakhairy/myPy/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/mnt/home.stud/zakhairy/myPy/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/mnt/home.stud/zakhairy/myPy/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 182, in _apply
    param.data = fn(param.data)
  File "/mnt/home.stud/zakhairy/myPy/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 249, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: torch.cuda.FloatTensor is not enabled.

**Comment by irazakharchenko** [comment]
the wrong installation of Pytorch, need installation with Cuda.

**Comment by Sun-Ziyi** [comment]
>           the wrong installation of Pytorch, need installation with Cuda.

@irazakharchenko  your meaning is that we should install CUDA to solve the problem???
