### ISSUE TITLE
[imagenet] Saved model is different from pretrained model

### ISSUE THREAD

**Issue by jamiechoi1995** [pytorch/examples#410]
I am using imagenet example code: https://github.com/pytorch/examples/blob/6fd43cd04f4677be005167157c848f0fefe131af/imagenet/main.py
 to finetune a pretrained model to apply for other tasks,

my code works well with pretrained resnet101 model: https://download.pytorch.org/models/resnet101-5d3b4d8f.pth
but get the error when I loading the model saved by the example code:

Traceback (most recent call last):
  File "scripts/prepro_mask_feats_hdf5.py", line 146, in <module>
    main(params)
  File "scripts/prepro_mask_feats_hdf5.py", line 75, in main
    net.load_state_dict(torch.load(os.path.join(params['model_root'],params['model']+'.pth')))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNet:
	Missing key(s) in state_dict: "conv1.weight", "bn1.running_var", "bn1.bias", "bn1.weight", "bn1.running_mean", "layer1.0.conv1.weight", "layer1.0.bn1.running_var", "layer1.0.bn1.bias", "layer1.0.bn1.weight", "layer1.0.bn1.running_mean", "layer1.0.conv2.weight", "layer1.0.bn2.running_var", "layer1.0.bn2.bias", "layer1.0.bn2.weight", "layer1.0.bn2.running_mean", "layer1.0.conv3.weight", "layer1.0.bn3.running_var", "layer1.0.bn3.bias", "layer1.0.bn3.weight", "layer1.0.bn3.running_mean", "layer1.0.downsample.0.weight", "layer1.0.downsample.1.running_var", "layer1.0.downsample.1.bias", "layer1.0.downsample.1.weight", "layer1.0.downsample.1.running_mean", "layer1.1.conv1.weight", "layer1.1.bn1.running_var", "layer1.1.bn1.bias", "layer1.1.bn1.weight", "layer1.1.bn1.running_mean", "layer1.1.conv2.weight", "layer1.1.bn2.running_var", "layer1.1.bn2.bias", "layer1.1.bn2.weight", "layer1.1.bn2.running_mean", "layer1.1.conv3.weight", "layer1.1.bn3.running_var", "layer1.1.bn3.bias", "layer1.1.bn3.weight", "layer1.1.bn3.running_mean", "layer1.2.conv1.weight", "layer1.2.bn1.running_var", "layer1.2.bn1.bias", "layer1.2.bn1.weight", "layer1.2.bn1.running_mean", "layer1.2.conv2.weight", "layer1.2.bn2.running_var", "layer1.2.bn2.bias", "layer1.2.bn2.weight", "layer1.2.bn2.running_mean", "layer1.2.conv3.weight", "layer1.2.bn3.running_var", "layer1.2.bn3.bias", "layer1.2.bn3.weight", "layer1.2.bn3.running_mean", "layer2.0.conv1.weight", "layer2.0.bn1.running_var", "layer2.0.bn1.bias", "layer2.0.bn1.weight", "layer2.0.bn1.running_mean", "layer2.0.conv2.weight", "layer2.0.bn2.running_var", "layer2.0.bn2.bias", "layer2.0.bn2.weight", "layer2.0.bn2.running_mean", "layer2.0.conv3.weight", "layer2.0.bn3.running_var", "layer2.0.bn3.bias", "layer2.0.bn3.weight", "layer2.0.bn3.running_mean", "layer2.0.downsample.0.weight", "layer2.0.downsample.1.running_var", "layer2.0.downsample.1.bias", "layer2.0.downsample.1.weight", "layer2.0.downsample.1.running_mean", "layer2.1.conv1.weight", "layer2.1.bn1.running_var", "layer2.1.bn1.bias", "layer2.1.bn1.weight", "layer2.1.bn1.running_mean", "layer2.1.conv2.weight", "layer2.1.bn2.running_var", "layer2.1.bn2.bias", "layer2.1.bn2.weight", "layer2.1.bn2.running_mean", "layer2.1.conv3.weight", "layer2.1.bn3.running_var", "layer2.1.bn3.bias", "layer2.1.bn3.weight", "layer2.1.bn3.running_mean", "layer2.2.conv1.weight", "layer2.2.bn1.running_var", "layer2.2.bn1.bias", "layer2.2.bn1.weight", "layer2.2.bn1.running_mean", "layer2.2.conv2.weight", "layer2.2.bn2.running_var", "layer2.2.bn2.bias", "layer2.2.bn2.weight", "layer2.2.bn2.running_mean", "layer2.2.conv3.weight", "layer2.2.bn3.running_var", "layer2.2.bn3.bias", "layer2.2.bn3.weight", "layer2.2.bn3.running_mean", "layer2.3.conv1.weight", "layer2.3.bn1.running_var", "layer2.3.bn1.bias", "layer2.3.bn1.weight", "layer2.3.bn1.running_mean", "layer2.3.conv2.weight", "layer2.3.bn2.running_var", "layer2.3.bn2.bias", "layer2.3.bn2.weight", "layer2.3.bn2.running_mean", "layer2.3.conv3.weight", "layer2.3.bn3.running_var", "layer2.3.bn3.bias", "layer2.3.bn3.weight", "layer2.3.bn3.running_mean", "layer3.0.conv1.weight", "layer3.0.bn1.running_var", "layer3.0.bn1.bias", "layer3.0.bn1.weight", "layer3.0.bn1.running_mean", "layer3.0.conv2.weight", "layer3.0.bn2.running_var", "layer3.0.bn2.bias", "layer3.0.bn2.weight", "layer3.0.bn2.running_mean", "layer3.0.conv3.weight", "layer3.0.bn3.running_var", "layer3.0.bn3.bias", "layer3.0.bn3.weight", "layer3.0.bn3.running_mean", "layer3.0.downsample.0.weight", "layer3.0.downsample.1.running_var", "layer3.0.downsample.1.bias", "layer3.0.downsample.1.weight", "layer3.0.downsample.1.running_mean", "layer3.1.conv1.weight", "layer3.1.bn1.running_var", "layer3.1.bn1.bias", "layer3.1.bn1.weight", "layer3.1.bn1.running_mean", "layer3.1.conv2.weight", "layer3.1.bn2.running_var", "layer3.1.bn2.bias", "layer3.1.bn2.weight", "layer3.1.bn2.running_mean", "layer3.1.conv3.weight", "layer3.1.bn3.running_var", "layer3.1.bn3.bias", "layer3.1.bn3.weight", "layer3.1.bn3.running_mean", "layer3.2.conv1.weight", "layer3.2.bn1.running_var", "layer3.2.bn1.bias", "layer3.2.bn1.weight", "layer3.2.bn1.running_mean", "layer3.2.conv2.weight", "layer3.2.bn2.running_var", "layer3.2.bn2.bias", "layer3.2.bn2.weight", "layer3.2.bn2.running_mean", "layer3.2.conv3.weight", "layer3.2.bn3.running_var", "layer3.2.bn3.bias", "layer3.2.bn3.weight", "layer3.2.bn3.running_mean", "layer3.3.conv1.weight", "layer3.3.bn1.running_var", "layer3.3.bn1.bias", "layer3.3.bn1.weight", "layer3.3.bn1.running_mean", "layer3.3.conv2.weight", "layer3.3.bn2.running_var", "layer3.3.bn2.bias", "layer3.3.bn2.weight", "layer3.3.bn2.running_mean", "layer3.3.conv3.weight", "layer3.3.bn3.running_var", "layer3.3.bn3.bias", "layer3.3.bn3.weight", "layer3.3.bn3.running_mean", "layer3.4.conv1.weight", "layer3.4.bn1.running_var", "layer3.4.bn1.bias", "layer3.4.bn1.weight", "layer3.4.bn1.running_mean", "layer3.4.conv2.weight", "layer3.4.bn2.running_var", "layer3.4.bn2.bias", "layer3.4.bn2.weight", "layer3.4.bn2.running_mean", "layer3.4.conv3.weight", "layer3.4.bn3.running_var", "layer3.4.bn3.bias", "layer3.4.bn3.weight", "layer3.4.bn3.running_mean", "layer3.5.conv1.weight", "layer3.5.bn1.running_var", "layer3.5.bn1.bias", "layer3.5.bn1.weight", "layer3.5.bn1.running_mean", "layer3.5.conv2.weight", "layer3.5.bn2.running_var", "layer3.5.bn2.bias", "layer3.5.bn2.weight", "layer3.5.bn2.running_mean", "layer3.5.conv3.weight", "layer3.5.bn3.running_var", "layer3.5.bn3.bias", "layer3.5.bn3.weight", "layer3.5.bn3.running_mean", "layer3.6.conv1.weight", "layer3.6.bn1.running_var", "layer3.6.bn1.bias", "layer3.6.bn1.weight", "layer3.6.bn1.running_mean", "layer3.6.conv2.weight", "layer3.6.bn2.running_var", "layer3.6.bn2.bias", "layer3.6.bn2.weight", "layer3.6.bn2.running_mean", "layer3.6.conv3.weight", "layer3.6.bn3.running_var", "layer3.6.bn3.bias", "layer3.6.bn3.weight", "layer3.6.bn3.running_mean", "layer3.7.conv1.weight", "layer3.7.bn1.running_var", "layer3.7.bn1.bias", "layer3.7.bn1.weight", "layer3.7.bn1.running_mean", "layer3.7.conv2.weight", "layer3.7.bn2.running_var", "layer3.7.bn2.bias", "layer3.7.bn2.weight", "layer3.7.bn2.running_mean", "layer3.7.conv3.weight", "layer3.7.bn3.running_var", "layer3.7.bn3.bias", "layer3.7.bn3.weight", "layer3.7.bn3.running_mean", "layer3.8.conv1.weight", "layer3.8.bn1.running_var", "layer3.8.bn1.bias", "layer3.8.bn1.weight", "layer3.8.bn1.running_mean", "layer3.8.conv2.weight", "layer3.8.bn2.running_var", "layer3.8.bn2.bias", "layer3.8.bn2.weight", "layer3.8.bn2.running_mean", "layer3.8.conv3.weight", "layer3.8.bn3.running_var", "layer3.8.bn3.bias", "layer3.8.bn3.weight", "layer3.8.bn3.running_mean", "layer3.9.conv1.weight", "layer3.9.bn1.running_var", "layer3.9.bn1.bias", "layer3.9.bn1.weight", "layer3.9.bn1.running_mean", "layer3.9.conv2.weight", "layer3.9.bn2.running_var", "layer3.9.bn2.bias", "layer3.9.bn2.weight", "layer3.9.bn2.running_mean", "layer3.9.conv3.weight", "layer3.9.bn3.running_var", "layer3.9.bn3.bias", "layer3.9.bn3.weight", "layer3.9.bn3.running_mean", "layer3.10.conv1.weight", "layer3.10.bn1.running_var", "layer3.10.bn1.bias", "layer3.10.bn1.weight", "layer3.10.bn1.running_mean", "layer3.10.conv2.weight", "layer3.10.bn2.running_var", "layer3.10.bn2.bias", "layer3.10.bn2.weight", "layer3.10.bn2.running_mean", "layer3.10.conv3.weight", "layer3.10.bn3.running_var", "layer3.10.bn3.bias", "layer3.10.bn3.weight", "layer3.10.bn3.running_mean", "layer3.11.conv1.weight", "layer3.11.bn1.running_var", "layer3.11.bn1.bias", "layer3.11.bn1.weight", "layer3.11.bn1.running_mean", "layer3.11.conv2.weight", "layer3.11.bn2.running_var", "layer3.11.bn2.bias", "layer3.11.bn2.weight", "layer3.11.bn2.running_mean", "layer3.11.conv3.weight", "layer3.11.bn3.running_var", "layer3.11.bn3.bias", "layer3.11.bn3.weight", "layer3.11.bn3.running_mean", "layer3.12.conv1.weight", "layer3.12.bn1.running_var", "layer3.12.bn1.bias", "layer3.12.bn1.weight", "layer3.12.bn1.running_mean", "layer3.12.conv2.weight", "layer3.12.bn2.running_var", "layer3.12.bn2.bias", "layer3.12.bn2.weight", "layer3.12.bn2.running_mean", "layer3.12.conv3.weight", "layer3.12.bn3.running_var", "layer3.12.bn3.bias", "layer3.12.bn3.weight", "layer3.12.bn3.running_mean", "layer3.13.conv1.weight", "layer3.13.bn1.running_var", "layer3.13.bn1.bias", "layer3.13.bn1.weight", "layer3.13.bn1.running_mean", "layer3.13.conv2.weight", "layer3.13.bn2.running_var", "layer3.13.bn2.bias", "layer3.13.bn2.weight", "layer3.13.bn2.running_mean", "layer3.13.conv3.weight", "layer3.13.bn3.running_var", "layer3.13.bn3.bias", "layer3.13.bn3.weight", "layer3.13.bn3.running_mean", "layer3.14.conv1.weight", "layer3.14.bn1.running_var", "layer3.14.bn1.bias", "layer3.14.bn1.weight", "layer3.14.bn1.running_mean", "layer3.14.conv2.weight", "layer3.14.bn2.running_var", "layer3.14.bn2.bias", "layer3.14.bn2.weight", "layer3.14.bn2.running_mean", "layer3.14.conv3.weight", "layer3.14.bn3.running_var", "layer3.14.bn3.bias", "layer3.14.bn3.weight", "layer3.14.bn3.running_mean", "layer3.15.conv1.weight", "layer3.15.bn1.running_var", "layer3.15.bn1.bias", "layer3.15.bn1.weight", "layer3.15.bn1.running_mean", "layer3.15.conv2.weight", "layer3.15.bn2.running_var", "layer3.15.bn2.bias", "layer3.15.bn2.weight", "layer3.15.bn2.running_mean", "layer3.15.conv3.weight", "layer3.15.bn3.running_var", "layer3.15.bn3.bias", "layer3.15.bn3.weight", "layer3.15.bn3.running_mean", "layer3.16.conv1.weight", "layer3.16.bn1.running_var", "layer3.16.bn1.bias", "layer3.16.bn1.weight", "layer3.16.bn1.running_mean", "layer3.16.conv2.weight", "layer3.16.bn2.running_var", "layer3.16.bn2.bias", "layer3.16.bn2.weight", "layer3.16.bn2.running_mean", "layer3.16.conv3.weight", "layer3.16.bn3.running_var", "layer3.16.bn3.bias", "layer3.16.bn3.weight", "layer3.16.bn3.running_mean", "layer3.17.conv1.weight", "layer3.17.bn1.running_var", "layer3.17.bn1.bias", "layer3.17.bn1.weight", "layer3.17.bn1.running_mean", "layer3.17.conv2.weight", "layer3.17.bn2.running_var", "layer3.17.bn2.bias", "layer3.17.bn2.weight", "layer3.17.bn2.running_mean", "layer3.17.conv3.weight", "layer3.17.bn3.running_var", "layer3.17.bn3.bias", "layer3.17.bn3.weight", "layer3.17.bn3.running_mean", "layer3.18.conv1.weight", "layer3.18.bn1.running_var", "layer3.18.bn1.bias", "layer3.18.bn1.weight", "layer3.18.bn1.running_mean", "layer3.18.conv2.weight", "layer3.18.bn2.running_var", "layer3.18.bn2.bias", "layer3.18.bn2.weight", "layer3.18.bn2.running_mean", "layer3.18.conv3.weight", "layer3.18.bn3.running_var", "layer3.18.bn3.bias", "layer3.18.bn3.weight", "layer3.18.bn3.running_mean", "layer3.19.conv1.weight", "layer3.19.bn1.running_var", "layer3.19.bn1.bias", "layer3.19.bn1.weight", "layer3.19.bn1.running_mean", "layer3.19.conv2.weight", "layer3.19.bn2.running_var", "layer3.19.bn2.bias", "layer3.19.bn2.weight", "layer3.19.bn2.running_mean", "layer3.19.conv3.weight", "layer3.19.bn3.running_var", "layer3.19.bn3.bias", "layer3.19.bn3.weight", "layer3.19.bn3.running_mean", "layer3.20.conv1.weight", "layer3.20.bn1.running_var", "layer3.20.bn1.bias", "layer3.20.bn1.weight", "layer3.20.bn1.running_mean", "layer3.20.conv2.weight", "layer3.20.bn2.running_var", "layer3.20.bn2.bias", "layer3.20.bn2.weight", "layer3.20.bn2.running_mean", "layer3.20.conv3.weight", "layer3.20.bn3.running_var", "layer3.20.bn3.bias", "layer3.20.bn3.weight", "layer3.20.bn3.running_mean", "layer3.21.conv1.weight", "layer3.21.bn1.running_var", "layer3.21.bn1.bias", "layer3.21.bn1.weight", "layer3.21.bn1.running_mean", "layer3.21.conv2.weight", "layer3.21.bn2.running_var", "layer3.21.bn2.bias", "layer3.21.bn2.weight", "layer3.21.bn2.running_mean", "layer3.21.conv3.weight", "layer3.21.bn3.running_var", "layer3.21.bn3.bias", "layer3.21.bn3.weight", "layer3.21.bn3.running_mean", "layer3.22.conv1.weight", "layer3.22.bn1.running_var", "layer3.22.bn1.bias", "layer3.22.bn1.weight", "layer3.22.bn1.running_mean", "layer3.22.conv2.weight", "layer3.22.bn2.running_var", "layer3.22.bn2.bias", "layer3.22.bn2.weight", "layer3.22.bn2.running_mean", "layer3.22.conv3.weight", "layer3.22.bn3.running_var", "layer3.22.bn3.bias", "layer3.22.bn3.weight", "layer3.22.bn3.running_mean", "layer4.0.conv1.weight", "layer4.0.bn1.running_var", "layer4.0.bn1.bias", "layer4.0.bn1.weight", "layer4.0.bn1.running_mean", "layer4.0.conv2.weight", "layer4.0.bn2.running_var", "layer4.0.bn2.bias", "layer4.0.bn2.weight", "layer4.0.bn2.running_mean", "layer4.0.conv3.weight", "layer4.0.bn3.running_var", "layer4.0.bn3.bias", "layer4.0.bn3.weight", "layer4.0.bn3.running_mean", "layer4.0.downsample.0.weight", "layer4.0.downsample.1.running_var", "layer4.0.downsample.1.bias", "layer4.0.downsample.1.weight", "layer4.0.downsample.1.running_mean", "layer4.1.conv1.weight", "layer4.1.bn1.running_var", "layer4.1.bn1.bias", "layer4.1.bn1.weight", "layer4.1.bn1.running_mean", "layer4.1.conv2.weight", "layer4.1.bn2.running_var", "layer4.1.bn2.bias", "layer4.1.bn2.weight", "layer4.1.bn2.running_mean", "layer4.1.conv3.weight", "layer4.1.bn3.running_var", "layer4.1.bn3.bias", "layer4.1.bn3.weight", "layer4.1.bn3.running_mean", "layer4.2.conv1.weight", "layer4.2.bn1.running_var", "layer4.2.bn1.bias", "layer4.2.bn1.weight", "layer4.2.bn1.running_mean", "layer4.2.conv2.weight", "layer4.2.bn2.running_var", "layer4.2.bn2.bias", "layer4.2.bn2.weight", "layer4.2.bn2.running_mean", "layer4.2.conv3.weight", "layer4.2.bn3.running_var", "layer4.2.bn3.bias", "layer4.2.bn3.weight", "layer4.2.bn3.running_mean", "fc.bias", "fc.weight". 
	Unexpected key(s) in state_dict: "state_dict", "epoch", "arch", "optimizer", "best_prec1".

Seems the model saved by example code lacks of some dicts.
Could anybody kindly take a look?

**Comment by jamiechoi1995** [comment]
The example didn't save all dict to the model: https://github.com/pytorch/examples/blob/6fd43cd04f4677be005167157c848f0fefe131af/imagenet/main.py#L187

However, after I modified the code to save_checkpoint(model, is_best) to save all the dicts,
I got another error:

Traceback (most recent call last):
  File "scripts/prepro_mask_feats_hdf5.py", line 146, in <module>
    main(params)
  File "scripts/prepro_mask_feats_hdf5.py", line 75, in main
    net.load_state_dict(torch.load(os.path.join(params['model_root'],params['model']+'.pth')))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 695, in load_state_dict
    state_dict = state_dict.copy()
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 532, in __getattr__
    type(self).__name__, name))
AttributeError: 'ResNet' object has no attribute 'copy'

**Comment by jamiechoi1995** [comment]
Using

save_checkpoint(model.state_dict(), is_best)

sovle this issue.
