### ISSUE TITLE
AttributeError: module 'torch.multiprocessing' has no attribute 'spawn'

### ISSUE THREAD

**Issue by sunwillz** [pytorch/examples#457]
when i want to train imagenet, i got follow error:

Traceback (most recent call last):
  File "main.py", line 390, in <module>
    main()
  File "main.py", line 107, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
AttributeError: module 'torch.multiprocessing' has no attribute 'spawn'

My command line:
python3 main.py -a vgg16 --lr 0.01 --dist-url 'tcp://127.0.0.1:9999' --dist-backend 'nccl' --multiprocessing-distributed /data1/imagenet/ILSVRC/Data/CLS-LOC

what should i do?

**Comment by sunwillz** [comment]
my pytorch:0.4.1
