### ISSUE TITLE
semaphore leaking

### ISSUE THREAD

**Issue by Akmazad** [pytorch/examples#538]
following the imagenet/main.py example, I am having the following error, just like @htlchh [comments here](https://github.com/pytorch/pytorch/issues/11727#issuecomment-447546030).

===
/apps/python3/3.6.7-gcc620/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/apps/python3/3.6.7-gcc620/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/apps/python3/3.6.7-gcc620/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/apps/python3/3.6.7-gcc620/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/apps/python3/3.6.7-gcc620/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/apps/python3/3.6.7-gcc620/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "/short/yr31/myacc/Data/DeepBrain/Scripts/search_dist_new.py", line 466, in <module>
    main()
  File "/short/yr31/myacc/Data/DeepBrain/Scripts/search_dist_new.py", line 99, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, config))
  File "/short/yr31/myacc/local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/short/yr31/myacc/local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 103, in join
    (error_index, name)
Exception: process 7 terminated with signal SIGKILL
=====

**Comment by ZhichengHuang** [comment]
Have you solved this issue? I have met the same problem.

**Comment by Akmazad** [comment]
No. I gave up.

**Comment by xyoungli** [comment]
i met the same problem~~~
and that generated thousands of <defunct> processes

**Comment by MichaelDylan77** [comment]
I'm still having this same issue. It seems like it has been rather long running, with issues going back almost a year. I run into this when using `break` while looping through the loader while training using `DistributedDataParallel` on a single node with multiple GPUs. Doesn't seem to happen when using a single GPU or CPU.

**Comment by ElegantLin** [comment]
@Akmazad How many GPUs did you use to reproduce this problem? It worked well when I used 8 GPUs on 2 nodes. However, it failed when I used 16 GPUs on 2 nodes. I referred to [this](https://github.com/pytorch/pytorch/issues/23720#issue-475994378) and both of you error messages are the same with me. 

Do you use a large scale of GPUs?

**Comment by ElegantLin** [comment]
@mdlockyer Do you fix it? If you made it, could you please provide more information about this?

**Comment by mdlockyer** [comment]
@ElegantLin It doesn't seem to be an actual issue that will effect the training in any way. It's related to the use of multiprocessing for distributed training, and multiprocessing for the data loader workers. Don't quote me on this, but seem to remember coming across some discussion related to this between some of the PyTorch devs and I believe their conclusion was that it may not be something that is fixable. @soumith, I'm right about that? 

I ended up just suppressing the warnings with the `environ['PYTHONWARNINGS'] = 'ignore:semaphore_tracker:UserWarning'` solution from [here](https://discuss.pytorch.org/t/issue-with-multiprocessing-semaphore-tracking/22943/4). It works perfectly and I don't have any issues.

**Comment by soumith** [comment]
>  @soumith, I'm right about that?

From what I know, yes
