### ISSUE TITLE
Run MNIST on my GPU and got error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by enhuiz** [pytorch/examples#548]
Hi, I have the following configuration (collected by [collect_env.py](https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py)):

```
Collecting environment information...
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2070
Nvidia driver version: 410.78
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.0.1.post2
[pip3] torchvision==0.2.2.post3
[conda] Could not collect
```

After I run:

```
$ CUDA_LAUNCH_BLOCKING=1 python3 main.py
```

I got the following error:

```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=265 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "main.py", line 117, in <module>
    main()
  File "main.py", line 110, in main
    train(args, model, device, train_loader, optimizer, epoch)
  File "main.py", line 34, in train
    output = model(data)
  File "/home/zniu/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "main.py", line 25, in forward
    x = F.relu(self.fc1(x))
  File "/home/zniu/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zniu/venv/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/zniu/venv/lib/python3.5/site-packages/torch/nn/functional.py", line 1352, in linear
    ret = torch.addmm(torch.jit._unwrap_optional(bias), input, weight.t())
RuntimeError: CUDA error: an illegal memory access was encountered
```
However, if I run it with `--no-cuda`, everything is fine.

What could be the problem?

**Comment by srossi93** [comment]
It could be due to cuDNN missing. Did you installed pytorch via anaconda?

**Comment by enhuiz** [comment]
> It could be due to cuDNN missing. Did you installed pytorch via anaconda?

Thanks for your reply.

I used pip3 to install pytorch. While I have just tried to use anaconda but got the same error.

After installing anaconda, the `collect_env.py` shows:

```
Collecting environment information...
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2070
Nvidia driver version: 410.78
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.14.3
[pip] numpydoc==0.8.0
[pip] torch==1.0.1.post2
[pip] torchvision==0.2.2
[conda] _tflow_select             2.3.0                       mkl  
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.2                      1  
[conda] mkl-service               1.1.2            py36h17a0993_4  
[conda] mkl_fft                   1.0.1            py36h3010b51_0  
[conda] mkl_random                1.0.1            py36h629b387_0  
[conda] pytorch                   1.0.1           py3.6_cuda10.0.130_cudnn7.4.2_2    pytorch
[conda] tensorflow                1.9.0           mkl_py36h6d6ce78_1  
[conda] tensorflow-base           1.9.0           mkl_py36h2ca6a6a_0  
[conda] torchvision               0.2.2                      py_3    pytorch
```
And I got the same error:
```
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 112, in main
    train(args, model, device, train_loader, optimizer, epoch)
  File "main.py", line 36, in train
    output = model(data)
  File "/home/zniu/applications/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "main.py", line 27, in forward
    x = F.relu(self.fc1(x))
  File "/home/zniu/applications/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zniu/applications/anaconda3/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/zniu/applications/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1352, in linear
    ret = torch.addmm(torch.jit._unwrap_optional(bias), input, weight.t())
RuntimeError: CUDA error: an illegal memory access was encountered
```

And I've found If I run `dmesg`, it will show

```
NVRM: Xid (PCI:0000:01:00): 31, Ch 00000028, engmask 00000101, intr 00000000
```

Could it be a hardware problem? I cannot run my own code either, the same Xid 31 error will appear, but the pytorch error messages differ.

**Comment by enhuiz** [comment]
> [NVIDIA docs](https://docs.nvidia.com/deploy/xid-errors/) lists xid31 as **GPU memory page fault** due to either driver fault or user app fault. What you could do is to try to run the script without pinning the memory ([here](https://github.com/pytorch/examples/blob/5df464c46cf321ed1cc3df1e670358d7f5ae1887/mnist/main.py#L89)) and see what happens.

I changed this
https://github.com/pytorch/examples/blob/5df464c46cf321ed1cc3df1e670358d7f5ae1887/mnist/main.py#L89
to
```python
kwargs = {'num_workers': 1, 'pin_memory': False} if use_cuda else {}
``` 

It is still not working. The errors are the same as before.

**Comment by enhuiz** [comment]
It was a hardware problem. I returned my GPU to the vendor and after they sent me a new one, the problem no longer exists.
