### ISSUE TITLE
dcgan example doesn't work

### ISSUE THREAD

**Issue by Times125** [pytorch/examples#567]
my code below here:
- the “dcgan.py” file
```
import torch.nn as nn
class Generator(nn.Module):
    def __init__(self, input_size, gen_units, output_size):
        super(Generator, self).__init__()
        self.conv1 = nn.Sequential(
            nn.ConvTranspose2d(input_size, gen_units * 8, kernel_size=4, stride=1, padding=0, bias=False),
            nn.BatchNorm2d(gen_units * 8),
            nn.ReLU(True)
        )
        self.conv2 = nn.Sequential(
            nn.ConvTranspose2d(gen_units * 8, gen_units * 4, kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(gen_units * 4),
            nn.ReLU(True)
        )
        
        self.conv3 = nn.Sequential(
            nn.ConvTranspose2d(gen_units * 4, gen_units * 2, kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(gen_units * 2),
            nn.ReLU(True)
        )
       
        self.conv4 = nn.Sequential(
            nn.ConvTranspose2d(gen_units * 2, gen_units, kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(gen_units),
            nn.ReLU(True)
        )
        
        self.out = nn.Sequential(
            nn.ConvTranspose2d(gen_units, output_size, kernel_size=4, stride=2, padding=1, bias=False),
            nn.Tanh()
        )

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        output = self.out(x)
        return output


class Discriminator(nn.Module):
    def __init__(self, input_size, dis_units):
        super(Discriminator, self).__init__()
        self.conv1 = nn.Sequential(
            # input is (input_size) x 64 x 64
            nn.Conv2d(input_size, dis_units, kernel_size=4, stride=1, padding=0, bias=False),
            nn.LeakyReLU(0.2, inplace=True),
            # state size. (dis_units) x 32 x 32
        )
        self.conv2 = nn.Sequential(
            # state size. (dis_units) x 32 x 32
            nn.Conv2d(dis_units, dis_units * 2, kernel_size=4, stride=1, padding=0, bias=False),
            nn.BatchNorm2d(dis_units * 2),
            nn.LeakyReLU(0.2, inplace=True),
            # state size. (dis_units*2) x 16 x 16
        )
        self.conv3 = nn.Sequential(
            # state size. (dis_units*2) x 16 x 16
            nn.Conv2d(dis_units * 2, dis_units * 4, kernel_size=4, stride=1, padding=0, bias=False),
            nn.BatchNorm2d(dis_units * 4),
            nn.LeakyReLU(0.2, inplace=True),
            # state size. (dis_units*4) x 8 x 8
        )
        self.conv4 = nn.Sequential(
            # state size. (dis_units*4) x 8 x 8
            nn.Conv2d(dis_units * 4, dis_units * 8, kernel_size=4, stride=1, padding=0, bias=False),
            nn.BatchNorm2d(dis_units * 8),
            nn.LeakyReLU(0.2, inplace=True),
            # state size. (dis_units*8) x 4 x 4
        )

        self.conv5 = nn.Sequential(
            # state size. (dis_units*8) x 4 x 4
            nn.Conv2d(dis_units * 8, 1, kernel_size=4, stride=1, padding=0, bias=False),
            nn.Sigmoid()
            # output a probability
        )

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        output = self.conv5(x)
        return output
```
- the "train.py" file
```
import torch.backends as K
import torch.nn as nn
import torchvision
import torch.utils.data
import matplotlib.pyplot as plt
import numpy as np
from dcgan import (Generator, Discriminator)

torch.manual_seed(12345)

# K.cudnn.benchmark = True
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')


nc = 3  # number of color channels in the images
nz = 100  # length of latent vector
ngf = 32  # relates to the depth of feature maps carried through the generator
ndf = 32  # sets the depth of feature maps propagated through the discriminator
batch_size = 32
epochs = 100

height = 50
width = 150


dataset = torchvision.datasets.ImageFolder(root='data',
                                           transform=torchvision.transforms.Compose([
                                               torchvision.transforms.Resize([height, width]),
                                               torchvision.transforms.ToTensor(),
                                               torchvision.transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                                           ]))


dataloader = torch.utils.data.DataLoader(dataset=dataset, batch_size=batch_size,
                                         shuffle=True)

# real_batch = next(iter(dataloader))
# plt.figure(figsize=(16, 16))
# plt.axis("off")
# plt.title("Training Images")
# plt.imshow(np.transpose(torchvision.utils.make_grid(real_batch[0].to(device)[:32], padding=2, normalize=True).cpu(),
#                         (1, 2, 0)))
# plt.savefig('tets.png', )


netG = Generator(input_size=nz, gen_units=ngf, output_size=nc).to(device)
netD = Discriminator(input_size=nc, dis_units=ndf).to(device)


criterion = nn.BCELoss()


optimizerG = torch.optim.Adam(netG.parameters(), lr=2E-4, betas=(0.5, 0.999))
optimizerD = torch.optim.Adam(netD.parameters(), lr=2E-4, betas=(0.5, 0.999))


fake_label = 0
real_label = 1

#  Create batch of latent vectors that we will use to visualize
#  the progression of the generator
fixed_noise = torch.randn(batch_size, nz, 1, 1, device=device)

img_list = []
G_losses = []
D_losses = []
iters = 0


for epoch in range(epochs):
    for i, (img, _) in enumerate(dataloader, 0):
        '''
        1) Update D network: maximize log(D(x)) + log(1 - D(G(z)))
        '''
        # train with real
        netD.zero_grad()
        img = img.to(device)
        label = torch.full((img.size(0),), real_label, device=device)

        output = netD(img).view(-1)  

        error_D_real = criterion(output, label) 

        error_D_real.backward()  
        D_x = output.mean().item()  

        # train with fake
        noise = torch.randn(img.size(0), nz, 1, 1, device=device)  
        fake = netG(noise)
        label.fill_(fake_label) 
        output = netD(fake.detach()).view(-1)
        error_D_fake = criterion(output, label) 
        error_D_fake.backward()
        D_G_z1 = output.mean().item()
        errD = error_D_real + error_D_fake
        optimizerD.step() 

        '''
        2) Update G network: maximize log(D(G(z)))
        '''
        netG.zero_grad()
        label.fill_(real_label)  # fake labels are real for generator cost
        output = netD(fake).view(-1)
        errG = criterion(output, label)
        errG.backward()
        D_G_z2 = output.mean().item()
        optimizerG.step()  # Update G

        if i % 50 == 0:
            print('[%d/%d][%d/%d]\tLoss_D: %.4f\tLoss_G: %.4f\tD(x): %.4f\tD(G(z)): %.4f / %.4f'
                  % (epoch, epochs, i, len(dataloader),
                     errD.item(), errG.item(), D_x, D_G_z1, D_G_z2))

            # Save Losses for plotting later
        G_losses.append(errG.item())
        D_losses.append(errD.item())

        # Check how the generator is doing by saving G's output on fixed_noise
        if (iters % 500 == 0) or ((epoch == epochs - 1) and (i == len(dataloader) - 1)):
            with torch.no_grad():
                fake = netG(fixed_noise).detach().cpu()
            img_list.append(torchvision.utils.make_grid(fake, padding=2, normalize=True))
        iters += 1
        torch.cuda.empty_cache()
```
these codes copy from dcgan example,but when I run it, some errors occur, below here:
```
Traceback (most recent call last):
  File "/home/xxx/captcha_experiment/train.py", line 82, in <module>
    error_D_real = criterion(output, label) 
  File "/root/anaconda3/envs/xxx_exp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/xxx_exp/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 512, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/root/anaconda3/envs/xxx_exp/lib/python3.6/site-packages/torch/nn/functional.py", line 2106, in binary_cross_entropy
    "!= input nelement ({})".format(target.numel(), input.numel()))
ValueError: Target and input must have the same number of elements. target nelement (32) != input nelement (151200)
```
The netD's output.shape doesn't match the label.shape. How could I solve it?

**Comment by sakaia** [comment]
In Google Colab, dcgan works

```
!wget https://s3.amazonaws.com/fast-ai-imageclas/imagenette-320.tgz
!tar xzf imagenette-320.tgz
```

```
!git clone https://github.com/pytorch/examples
!cd examples/dcgan; python3 main.py --dataset imagenet --dataroot ../../imagenette-320 --cuda
```

**Comment by Times125** [comment]
> In Google Colab, dcgan works
> 
> ```
> !wget https://s3.amazonaws.com/fast-ai-imageclas/imagenette-320.tgz
> !tar xzf imagenette-320.tgz
> ```
> 
> ```
> !git clone https://github.com/pytorch/examples
> !cd examples/dcgan; python3 main.py --dataset imagenet --dataroot ../../imagenette-320 --cuda
> ```

I ran it at local platform, my pic size is 50*150. Do u have any idea to alter the code ? thanks.

**Comment by msaroufim** [comment]
@Times125 I'd try a fresh environment as is it's not clear how I can help repro. Please reopen if I'm mistaken

**Comment by Times125** [comment]
您好，我已经收到您的来信，会尽快处理。
