### ISSUE TITLE
Problem finding the model en

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/examples#598]
Hi,
How can I resolve this error?
```
$ python train.py 
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    inputs = data.Field(lower=args.lower, tokenize='spacy')
  File "/home/mahmood/.local/lib/python2.7/site-packages/torchtext/data/field.py", line 152, in __init__
    self.tokenize = get_tokenizer(tokenize)
  File "/home/mahmood/.local/lib/python2.7/site-packages/torchtext/data/utils.py", line 12, in get_tokenizer
    spacy_en = spacy.load('en')
  File "/home/mahmood/.local/lib/python2.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/mahmood/.local/lib/python2.7/site-packages/spacy/util.py", line 139, in load_model
    raise IOError(Errors.E050.format(name=name))
IOError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

```

**Comment by charleshofer** [comment]
Try running `python -m spacy download en`
