### ISSUE TITLE
GoogleNet error

### ISSUE THREAD

**Issue by deepali-c** [pytorch/examples#617]
Observed the following error while trying to run `googlenet` model:

```
$ python main.py -a googlenet -b 64 --epochs 2  <myimagenetdir>
=> creating model 'googlenet'
Traceback (most recent call last):
  File "main.py", line 437, in <module>
    main()
  File "main.py", line 121, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 257, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "main.py", line 299, in train
    output = model(input)
  File "<myenv>/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "<myenv>/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "<myenv>/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "<myenv>/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "<myenv>/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: __new__() missing 2 required positional arguments: 'aux_logits2' and 'aux_logits1'
```

Then came across https://github.com/pytorch/examples/pull/560 and https://github.com/pytorch/vision/pull/678. 

Shall I raise a PR to remove `googlenet` from supported models in `imagenet/main.py`.

**Comment by soumith** [comment]
that would be great, thanks deepali!

**Comment by msaroufim** [comment]
`googlenet` no longer shows up anywhere in the `imagenet` directory
