### ISSUE TITLE
mnist example is failing

### ISSUE THREAD

**Issue by JunpuFan** [pytorch/examples#725]
The mnist example is failing on master branch(The error log provided below). 
```
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to ../data/MNIST/raw/train-images-idx3-ubyte.gz
-819200.0%Traceback (most recent call last):
  File "main.py", line 40, in <module>
    transforms.Normalize((0.1307,), (0.3081,))
  File "/home/ubuntu/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/torchvision/datasets/mnist.py", line 70, in __init__
    self.download()
  File "/home/ubuntu/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/torchvision/datasets/mnist.py", line 137, in download
    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename, md5=md5)
  File "/home/ubuntu/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/torchvision/datasets/utils.py", line 264, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/ubuntu/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/torchvision/datasets/utils.py", line 100, in download_url
    raise RuntimeError("File not found or corrupted.")
RuntimeError: File not found or corrupted.
testPyTorch : TEST FAILED
```
torchvision used `torchvision  0.5.0  py27_cu101  from conda channel pytorch`

After investigate on my end, I found that the md5 hash used in `torchvision/datasets/mnist.py` is wrong.
```
resources = [
        ("http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz", "f68b3c2dcbeaaa9fbdd348bbdeb94873"),
      ...
    ]
```
Above code defined the md5 hash to be `f68b3c2dcbeaaa9fbdd348bbdeb94873` however when I run `md5sum` the output is `4f20b85ce5ebf225720e040314a7966a`
```
md5sum train-images-idx3-ubyte.gz
4f20b85ce5ebf225720e040314a7966a  train-images-idx3-ubyte.gz
```

**Comment by zhangguanheng66** [comment]
The issue has been tracked in a separate issue.
https://github.com/pytorch/vision/issues/1938
