### ISSUE TITLE
Error while running distributed/rpc/parameter_server

### ISSUE THREAD

**Issue by panchul** [pytorch/examples#772]
I can reproduce it with wither two nodes, or on a single node(with two processes). I also tried running with or with GPUs enabled, and in 3-node clusters. Getting an error while running the `distributed/rpc/parameter_server` sample.

As `Readme.md` instructed, I ran:

1. The master (rank 0): `python rpc_parameter_server.py --world_size=2 --rank=0`.
2. Then, in another terminal, the worker (rank 1):  `python rpc_parameter_server.py --world_size=2 --rank=1`.

The worker does the training and returns an error(posting the output below. I looked at the `torch/nn/modules/module.py` and indeed the signature of `self.forward()` seems to be wrong). After that, the  master produces an error about rpc agent.
 
Here is the output of the master node:

```
$ python rpc_parameter_server.py --world_size=2 --rank=0
using master_addr localhost
using master_port 29500
using world_size 2
PS master initializing RPC
RPC initialized! Running parameter server...
Using 0 GPUs to train
Putting first 2 convs on cpu
Putting rest of layers on cpu
[E process_group_agent.cpp:664] Encountered exception in ProcessGroupAgent::listenLoop(): [/opt/conda/conda-bld/pytorch_1587428398394/work/third_party/gloo/gloo/transport/tcp/pair.cc:566] Read error [192.168.9.4]:28296: Connection reset by peer on worker 0. This means that the RPC agent is in an unhealthy state and unusable.
``` 

And this is how the worker(in a separate terminal):

```
$  python rpc_parameter_server.py --world_size=2 --rank=1
Worker rank 1 initializing RPC
Worker 1 done initializing RPC
Rank 1 training batch 0 loss 2.3020286560058594
Rank 1 training batch 5 loss 2.1532726287841797
... skipping more batches here ...
Rank 1 training batch 1865 loss 0.16555693745613098
Rank 1 training batch 1870 loss 0.06451829522848129
Training complete!
Getting accuracy....
Process Process-1:
Traceback (most recent call last):
  File "/anaconda/envs/py37_default/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/anaconda/envs/py37_default/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "rpc_parameter_server.py", line 224, in run_worker
    run_training_loop(rank, num_gpus, train_loader, test_loader)
  File "rpc_parameter_server.py", line 194, in run_training_loop
    get_accuracy(test_loader, net)
  File "rpc_parameter_server.py", line 205, in get_accuracy
    out = model(data, -1)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
```

**Comment by soumith** [comment]
cc: @osalpekar @mrshenli

**Comment by osalpekar** [comment]
@panchul I think #774 should fix this

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/examples/pull/774

**Comment by zhilonglu** [comment]
@panchul hello, recently i want to run rpc on two physical machines, how to run the py file. can u share command. The two machines are cpu and gpu. Thanks.
