### ISSUE TITLE
How to use torch.multiprocessing in Windows

### ISSUE THREAD

**Issue by zhong-xin** [pytorch/examples#806]
The following error occurred when I used the torch.multiprocessing [demo](https://github.com/pytorch/examples/tree/master/mnist_hogwild) provided by Pytorch.

C:\Users\user\anaconda3\python.exe D:/HPO-Pro/PBT3/main_demo.py
cuda
cuda
THCudaCheck FAIL file=..\torch/csrc/generic/StorageSharing.cpp line=247 error=801 : operation not supported
Traceback (most recent call last):
  File "D:/HPO-Pro/PBT3/main_demo.py", line 88, in <module>
    p.start()
  File "C:\Users\user\anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\user\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\user\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\user\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\user\anaconda3\lib\site-packages\torch\multiprocessing\reductions.py", line 240, in reduce_tensor
    event_sync_required) = storage._share_cuda_()
RuntimeError: cuda runtime error (801) : operation not supported at ..\torch/csrc/generic/StorageSharing.cpp:247

Can't I use CUDA while using torch.multiprocessing in Windows?

**Comment by ryangooch** [comment]
multiprocessing in Windows is tough. A workaround however is training the model with `--threads 0`

**Comment by shtse8** [comment]
> --threads 0

what is `--threads 0`?
I have the same issue on multiprocessing with cuda in windows. what can I do if I want to do multiprocessing with cuda in windows?

**Comment by ryangooch** [comment]
When you run the training/evaluation from the command line, you have several options that you can use to impact how the model trains on your device. The threads option tells the script how many multiprocessing threads to use.

Multiprocessing on Windows is hard. For me, the workaround is simply not to use multiprocessing when doing any kind of analysis on Windows.

```--threads 0``` basically turns off multiprocessing. The best way to do multiprocessing with CUDA in Windows is to not do it.

**Comment by zhong-xin** [comment]
Ok, I konw.Thank you for response.

**Comment by zhong-xin** [comment]
> When you run the training/evaluation from the command line, you have several options that you can use to impact how the model trains on your device. The threads option tells the script how many multiprocessing threads to use.
> 
> Multiprocessing on Windows is hard. For me, the workaround is simply not to use multiprocessing when doing any kind of analysis on Windows.
> 
> `--threads 0` basically turns off multiprocessing. The best way to do multiprocessing with CUDA in Windows is to not do it.

Ok, I konw.Thank you for response.
