### ISSUE TITLE
imagenet fails with view size is not compatible with input tensor's size and stride

### ISSUE THREAD

**Issue by seemethere** [pytorch/examples#836]
Currently testing out the new `v1.7.0-rc2` from `pytorch/pytorch` and experiencing an issue that I wasn't experiencing with the `v1.6.0` release:

```
$ cd imagenet
$ python -u main.py --epochs 3 /datasets01/imagenet_full_size/061417
=> creating model 'resnet18'
Traceback (most recent call last):
  File "main.py", line 429, in <module>
    main()
  File "main.py", line 112, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 245, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "main.py", line 294, in train
    acc1, acc5 = accuracy(output, target, topk=(1, 5))
  File "main.py", line 423, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0, keepdim=True)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

I've switched the above line to use `reshape` but it does come with a performance impact of about 200MB more of CPU RSS Memory usage. I was wondering if this is a regression of some sort?

**Comment by soumith** [comment]
cc: @ngimel @VitalyFedyunin

**Comment by seemethere** [comment]
Resolved, going to change the `view` to `reshape`.

Performance impact seems unrelated to that change.
