### ISSUE TITLE
torchvision.datasets.ImageNet

### ISSUE THREAD

**Issue by slmatrix** [pytorch/examples#838]
The imagenet dataset cannot be downloaded.
To reproduce, please try on PyTorch 1.2.0: 

```
trainset    = torchvision.datasets.ImageNet(root=DATA_DIR, train=True, download=True);
```

```
Downloading http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_devkit_t12.tar.gz to /home/root/dataset/ILSVRC2012_devkit_t12.tar.gz
0it [00:00, ?it/s]Traceback (most recent call last):
  File "imagenet_train.py", line 219, in <module>
    transform=transform_train
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/imagenet.py", line 55, in __init__
    self.download()
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/imagenet.py", line 75, in download
    md5=archive_dict['md5'])
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/utils.py", line 248, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/utils.py", line 96, in download_url
    raise e
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/utils.py", line 84, in download_url
    reporthook=gen_bar_updater()
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
0it [00:00, ?it/s]
```

**Comment by slmatrix** [comment]
The 'official' website requests downloads from [https://www.kaggle.com/c/imagenet-object-localization-challenge/data].

Closing the issue unless a PR is needed.
