### ISSUE TITLE
DDP on GPUs invalid ordinal

### ISSUE THREAD

**Issue by ccijunk** [pytorch/examples#885]
there is a node with 8 gpus，and I can't train my model on any 4 of the gpus, except gpu-id is 0,1,2,3.
how can I use any permutation and combination of the 8 gpus? Thanks 

`-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/lab-chen.qi/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/lab-chen.qi/sc/resweightv1/tiny_imagenet_multi.py", line 223, in main_worker
    torch.cuda.set_device(gpu)
  File "/home/lab-chen.qi/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/cuda/__init__.py", line 263, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal`

some of my code

`def  main():
    os.environ['CUDA_VISIBLE_DEVICES'] = args.gpu_id
    ngpus_per_node = args.gpu_id.split(',').__len__()
    args.nprocs = ngpus_per_node
    args.world_size = ngpus_per_node * args.world_size
    args.lr = args.lr * args.world_size
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args,state))

def main_worker(local_rank,ngpus_per_node,args,state):

    start_epoch = args.start_epoch  # start from epoch 0 or last checkpoint epoch

    gpus = os.environ['CUDA_VISIBLE_DEVICES'].split(',')
    gpu = int(gpus[local_rank])
    args.gpu = gpu

    args.rank = args.rank * ngpus_per_node + local_rank#args.gpu[gpu]
    print('rank: {} / {}'.format(args.rank, args.world_size))

    dist.init_process_group(backend=args.dist_backend,
                            init_method=args.dist_url,
                            world_size=args.world_size,
                            rank=args.rank)

    torch.cuda.set_device(gpu)
`

**Comment by ccijunk** [comment]
I try this, but it doesn't work [https://github.com/PyTorchLightning/pytorch-lightning/issues/3791](https://github.com/PyTorchLightning/pytorch-lightning/issues/3791)

**Comment by weixsong** [comment]
I meet the same issue with you when using DDP. Is there any solution for this issue?
